import './App.css';

// Json file generated by toncli
// just link it to dapp with: ln -s build/nft_sale.json dapp/src/
const toncli_project = require("./nft_sale.json");


function App() {
    console.log(toncli_project);
    return (
        <div className="App">
            <header className="App-header">
                <p>Hi there</p>
            </header>
        </div>
    );
}

export default App;
